steps:
  - name: "build image"
    plugins:
      - docker-compose#v3.7.0:
          build: app
          config: .buildkite/docker-compose.yml

  - wait

  - name: "linting"
    command:
      - ".buildkite/scripts/linting.sh"
    plugins:
      - docker-compose#v3.7.0:
          run: app
          config: .buildkite/docker-compose.yml

  - wait

  - name: "auth0-script-packaging"
    command:
      - ".buildkite/scripts/auth0-script-packaging.sh"
    plugins:
      - wellcomecollection/aws-assume-role#v0.2.2:
          role: "arn:aws:iam::770700576653:role/identity-ci"
      - docker-compose#v3.7.0:
          run: app
          config: .buildkite/docker-compose.yml
          env:
            - BUILDKITE_BRANCH
            - AWS_ACCESS_KEY_ID
            - AWS_SECRET_ACCESS_KEY
            - AWS_SESSION_TOKEN

  - name: "aws-lambda-packaging"
    command:
      - "yarn install"
      - "yarn run -- lerna run build"
      - ".buildkite/scripts/aws-lambda-packaging.sh"
    plugins:
      - wellcomecollection/aws-assume-role#v0.2.2:
          role: "arn:aws:iam::770700576653:role/identity-ci"
      - docker-compose#v3.7.0:
          run: app
          config: .buildkite/docker-compose.yml
          env:
            - BUILDKITE_BRANCH
            - AWS_ACCESS_KEY_ID
            - AWS_SECRET_ACCESS_KEY
            - AWS_SESSION_TOKEN
