steps:
  - block: "deployment-parameters"
    if: "build.source == ui"
    fields:
      - select: "Environment"
        key: "deploy-environment"
        default: "stage"
        options:
          - label: "Staging"
            value: "stage"
          - label: "Production"
            value: "prod"
      - select: "API Gateway Stage"
        key: "deploy-api-gateway-stage"
        default: "v1"
        options:
          - label: "V1"
            value: "v1"

  - name: "auth0-script-deployment"
    if: "build.source != webhook"
    command:
      - ".buildkite/scripts/init-environment.sh"
      - ".buildkite/scripts/auth0-script-deployment.sh"
    plugins:
      - docker-compose#v3.7.0:
          run: app
          config: .buildkite/docker-compose.yml
          mount-buildkite-agent: true
          env:
            - BUILDKITE_BRANCH
            - DEPLOY_ENVIRONMENT
            - DEPLOY_API_GATEWAY_STAGE
